// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transit_display_platform_api.Data;

#nullable disable

namespace transit_display_platform_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804124925_BusAllocationAndOperations")]
    partial class BusAllocationAndOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("transit_display_platform_api.Schema.AcademicYearMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("UX_academic_year_master_IsCurrent")
                        .HasFilter("[IsCurrent] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("YearName")
                        .IsUnique()
                        .HasDatabaseName("UX_academic_year_master_YearName")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("academic_year_master");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2027, 4, 30),
                            IsActive = true,
                            IsCurrent = true,
                            IsDeleted = false,
                            StartDate = new DateOnly(2026, 6, 1),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearName = "2026-2027"
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("BoardingEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("BoardingEventId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("IX_audit_log_Session_CreatedAt");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BoardingEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("QueueOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacedByBusId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacesEventId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ReplacedByBusId");

                    b.HasIndex("ReplacesEventId");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("IX_boarding_events_RouteId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SessionId", "BusId")
                        .IsUnique()
                        .HasDatabaseName("UX_boarding_events_Session_Bus")
                        .HasFilter("[IsDeleted] = 0 AND [Status] <> 'Departed' AND [Status] <> 'Replaced'");

                    b.HasIndex("SessionId", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("UX_boarding_events_Session_Platform")
                        .HasFilter("[IsDeleted] = 0 AND [PlatformId] IS NOT NULL AND [Status] IN ('Arrived','Boarding')");

                    b.HasIndex("SessionId", "Status", "QueueOrder")
                        .HasDatabaseName("IX_boarding_events_Session_Status_Queue");

                    b.ToTable("boarding_events", t =>
                        {
                            t.HasCheckConstraint("CK_boarding_events_Status", "[Status] IN ('Waiting','Arrived','Boarding','Departed','Replaced')");
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BusRouteAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .IsUnique()
                        .HasDatabaseName("UX_bus_route_allocation_Standing_Bus")
                        .HasFilter("[AllocationType] = 'Standing' AND [EffectiveTo] IS NULL AND [IsDeleted] = 0");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RouteId")
                        .IsUnique()
                        .HasDatabaseName("UX_bus_route_allocation_Standing_Route")
                        .HasFilter("[AllocationType] = 'Standing' AND [EffectiveTo] IS NULL AND [IsDeleted] = 0");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("BusId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_bus_route_allocation_Override_Bus")
                        .HasFilter("[AllocationType] = 'Override' AND [IsDeleted] = 0");

                    b.HasIndex("RouteId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_bus_route_allocation_Override_Route")
                        .HasFilter("[AllocationType] = 'Override' AND [IsDeleted] = 0");

                    b.HasIndex("BusId", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_bus_route_allocation_Bus_Dates");

                    b.HasIndex("RouteId", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_bus_route_allocation_Route_Dates");

                    b.ToTable("bus_route_allocation", t =>
                        {
                            t.HasCheckConstraint("CK_bus_route_allocation_Dates", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_bus_route_allocation_Type", "[AllocationType] IN ('Standing','Override')");
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BusesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_buses_master_BusNumber")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RouteId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("buses_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CityMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RegionId");

                    b.HasIndex("StateId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("city_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CountryMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("country_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.DisplayMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FilterByGateId")
                        .HasColumnType("int");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScreenSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("VisibleRowCount")
                        .HasColumnType("int");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisplayCode")
                        .IsUnique()
                        .HasDatabaseName("UX_display_master_DisplayCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("FilterByGateId");

                    b.HasIndex("GateId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("display_master", t =>
                        {
                            t.HasCheckConstraint("CK_display_master_DisplayType", "[DisplayType] IN ('Outdoor','Indoor')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionStatus = "Unknown",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCode = "OUT-G6",
                            DisplayName = "Outdoor Video Wall - Gate No. 6",
                            DisplayType = "Outdoor",
                            GateId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Gate No. 6 entrance",
                            ScreenSize = "8x8",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VisibleRowCount = 25
                        },
                        new
                        {
                            Id = 2,
                            ConnectionStatus = "Unknown",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCode = "IND-E1",
                            DisplayName = "Indoor Video Wall - Exit 1",
                            DisplayType = "Indoor",
                            FilterByGateId = 3,
                            GateId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "School building exit 1",
                            ScreenSize = "4x6",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VisibleRowCount = 12
                        },
                        new
                        {
                            Id = 3,
                            ConnectionStatus = "Unknown",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayCode = "IND-E2",
                            DisplayName = "Indoor Video Wall - Exit 2",
                            DisplayType = "Indoor",
                            FilterByGateId = 4,
                            GateId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "School building exit 2",
                            ScreenSize = "4x6",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VisibleRowCount = 12
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.GateMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("GateCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GateCode")
                        .IsUnique()
                        .HasDatabaseName("UX_gate_master_GateCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedById");

                    b.ToTable("gate_master", t =>
                        {
                            t.HasCheckConstraint("CK_gate_master_GateType", "[GateType] IN ('BusEntry','BusExit','StudentExit')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GateCode = "G6",
                            GateName = "Gate No. 6 (Bus Entry)",
                            GateType = "BusEntry",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GateCode = "G1",
                            GateName = "Gate No. 1 (Bus Exit)",
                            GateType = "BusExit",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GateCode = "EXIT1",
                            GateName = "School Building Exit 1",
                            GateType = "StudentExit",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GateCode = "EXIT2",
                            GateName = "School Building Exit 2",
                            GateType = "StudentExit",
                            IsActive = true,
                            IsDeleted = false,
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.MenuAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("menu_assignment");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.MenuMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("menu_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.ParentMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AltMobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IdProofNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdProofType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWhatsAppEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PinCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MobileNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_parent_master_MobileNumber")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PinCodeId");

                    b.HasIndex("StateId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("parent_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.PinCodeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("pincode_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.PlatformsMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NearestGateId")
                        .HasColumnType("int");

                    b.Property<string>("PlatformName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlatformNumber")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NearestGateId");

                    b.HasIndex("PlatformNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_platforms_master_PlatformNumber")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedById");

                    b.ToTable("platforms_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RegionMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("region_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("role_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoutesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LedDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RouteCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RouteCode")
                        .IsUnique()
                        .HasDatabaseName("UX_routes_master_RouteCode")
                        .HasFilter("[IsDeleted] = 0 AND [RouteCode] IS NOT NULL");

                    b.HasIndex("UpdatedById");

                    b.ToTable("routes_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.Sessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResetAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("ShiftName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("SessionDate", "ShiftName")
                        .IsUnique()
                        .HasDatabaseName("UX_dispersal_sessions_Date_Shift")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("SessionDate", "Status")
                        .HasDatabaseName("IX_dispersal_sessions_Date_Status");

                    b.ToTable("dispersal_sessions");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StateMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("StateCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RegionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("state_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StudentMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("BusId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassTeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DropStop")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ExitGateId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PickupStop")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RfidTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<bool>("UsesTransport")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .HasDatabaseName("IX_student_master_BusId");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExitGateId");

                    b.HasIndex("RfidTag")
                        .IsUnique()
                        .HasDatabaseName("UX_student_master_RfidTag")
                        .HasFilter("[IsDeleted] = 0 AND [RfidTag] IS NOT NULL");

                    b.HasIndex("RouteId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("AdmissionNumber", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("UX_student_master_Admission_Year")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("AcademicYearId", "Grade", "Division")
                        .HasDatabaseName("IX_student_master_Class");

                    b.ToTable("student_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StudentParentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactPriority")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthorisedForPickup")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmergencyContact")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("ReceivesNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_student_parent_mapping_ParentId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_student_parent_mapping_OnePrimary")
                        .HasFilter("[IsPrimaryContact] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("StudentId", "ParentId")
                        .IsUnique()
                        .HasDatabaseName("UX_student_parent_mapping_Student_Parent")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("student_parent_mapping", t =>
                        {
                            t.HasCheckConstraint("CK_student_parent_mapping_Relation", "[Relation] IN ('Father','Mother','Guardian','Grandfather','Grandmother','Uncle','Aunt','Sibling','Driver','Other')");
                        });
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Contact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EmailId")
                        .IsUnique()
                        .HasDatabaseName("UX_user_master_EmailId")
                        .HasFilter("[IsDeleted] = 0 AND [EmailId] IS NOT NULL");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_user_master_EmployeeCode")
                        .HasFilter("[IsDeleted] = 0 AND [EmployeeCode] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("user_master");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.AcademicYearMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_academic_year_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_academic_year_master_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.AuditLog", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.BoardingEvents", "BoardingEvent")
                        .WithMany()
                        .HasForeignKey("BoardingEventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RoleMaster", "Role")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.Sessions", "Session")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_user_master_UpdatedById");

                    b.Navigation("ActorUser");

                    b.Navigation("BoardingEvent");

                    b.Navigation("Role");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BoardingEvents", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.BusesMaster", "Bus")
                        .WithMany("BoardingEvents")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_boarding_events_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.PlatformsMaster", "Platform")
                        .WithMany("BoardingEvents")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.BusesMaster", "ReplacedByBus")
                        .WithMany()
                        .HasForeignKey("ReplacedByBusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.BoardingEvents", "ReplacesEvent")
                        .WithMany()
                        .HasForeignKey("ReplacesEventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.RoutesMaster", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.Sessions", "Session")
                        .WithMany("BoardingEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_boarding_events_user_master_UpdatedById");

                    b.Navigation("Bus");

                    b.Navigation("Platform");

                    b.Navigation("ReplacedByBus");

                    b.Navigation("ReplacesEvent");

                    b.Navigation("Route");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BusRouteAllocation", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.BusesMaster", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_bus_route_allocation_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RoutesMaster", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_bus_route_allocation_user_master_UpdatedById");

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BusesMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_buses_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RoutesMaster", "Route")
                        .WithMany("Buses")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_buses_master_user_master_UpdatedById");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CityMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_city_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RegionMaster", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.StateMaster", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_city_master_user_master_UpdatedById");

                    b.Navigation("Region");

                    b.Navigation("State");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CountryMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_country_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_country_master_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.DisplayMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_display_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.GateMaster", "FilterByGate")
                        .WithMany()
                        .HasForeignKey("FilterByGateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.GateMaster", "Gate")
                        .WithMany("Displays")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_display_master_user_master_UpdatedById");

                    b.Navigation("FilterByGate");

                    b.Navigation("Gate");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.GateMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_gate_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_gate_master_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.MenuAssignment", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_menu_assignment_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.MenuMaster", "Menu")
                        .WithMany("MenuAssignments")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.RoleMaster", "Role")
                        .WithMany("MenuAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_menu_assignment_user_master_UpdatedById");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.MenuMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_menu_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.MenuMaster", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_menu_master_user_master_UpdatedById");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.ParentMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.CityMaster", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_parent_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.PinCodeMaster", "PinCode")
                        .WithMany()
                        .HasForeignKey("PinCodeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.StateMaster", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_parent_master_user_master_UpdatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("PinCode");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.PinCodeMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.CityMaster", "City")
                        .WithMany("PinCodes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_pincode_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_pincode_master_user_master_UpdatedById");

                    b.Navigation("City");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.PlatformsMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_platforms_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.GateMaster", "NearestGate")
                        .WithMany("Platforms")
                        .HasForeignKey("NearestGateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_platforms_master_user_master_UpdatedById");

                    b.Navigation("NearestGate");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RegionMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.CountryMaster", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_region_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_region_master_user_master_UpdatedById");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoleMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_role_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_role_master_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoutesMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_routes_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_routes_master_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.Sessions", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_dispersal_sessions_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_dispersal_sessions_user_master_UpdatedById");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StateMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.CountryMaster", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_state_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RegionMaster", "Region")
                        .WithMany("States")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_state_master_user_master_UpdatedById");

                    b.Navigation("Country");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StudentMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.AcademicYearMaster", "AcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.BusesMaster", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_student_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.GateMaster", "ExitGate")
                        .WithMany()
                        .HasForeignKey("ExitGateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.RoutesMaster", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_student_master_user_master_UpdatedById");

                    b.Navigation("AcademicYear");

                    b.Navigation("Bus");

                    b.Navigation("ClassTeacher");

                    b.Navigation("ExitGate");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StudentParentMapping", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_student_parent_mapping_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.ParentMaster", "Parent")
                        .WithMany("StudentMappings")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.StudentMaster", "Student")
                        .WithMany("ParentMappings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_student_parent_mapping_user_master_UpdatedById");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.UserMaster", b =>
                {
                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_user_master_user_master_CreatedById");

                    b.HasOne("transit_display_platform_api.Schema.RoleMaster", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("transit_display_platform_api.Schema.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_user_master_user_master_UpdatedById");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.AcademicYearMaster", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.BusesMaster", b =>
                {
                    b.Navigation("BoardingEvents");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CityMaster", b =>
                {
                    b.Navigation("PinCodes");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.CountryMaster", b =>
                {
                    b.Navigation("Regions");

                    b.Navigation("States");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.GateMaster", b =>
                {
                    b.Navigation("Displays");

                    b.Navigation("Platforms");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.MenuMaster", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuAssignments");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.ParentMaster", b =>
                {
                    b.Navigation("StudentMappings");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.PlatformsMaster", b =>
                {
                    b.Navigation("BoardingEvents");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RegionMaster", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoleMaster", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("MenuAssignments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.RoutesMaster", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.Sessions", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BoardingEvents");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StateMaster", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("transit_display_platform_api.Schema.StudentMaster", b =>
                {
                    b.Navigation("ParentMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
